export * from './mensaje.interface';
export * from './emisor.interface';
export * from './canal.interface';
export * from './rele.interface';
export * from './receptor.interface';
export * from './nodo.interface';
export * from './codificador.interface';
export * from './error-transmision.interface';
export * from './componente-registro.interface';
